name: Example GitHub Action

on:
  push:
    branches:
      - main
  workflow_dispatch:  # Manually triggered workflow

jobs:
  example_job:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set environment variables
        run: |
          VARIABLES=$(cat variables.yml)
          echo "$VARIABLES" | yq -r '.variables | to_entries[] | "export \(.key)=\(.value)"' >> $GITHUB_ENV

      - name: Print Krishna's Age
        run: echo "Krishna's age is $krishna_age"

      - name: Print Manoj's City
        run: echo "Manoj lives in $krishna_city"
